CepteFaturaMvc/Models/Email.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CepteFaturaMvc.Models
{
    public class Email
    {
        public string ad { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string konu { get; set; }
        public string mesaj { get; set; }

    }


    public class Message
    {
        public bool IsSuccess { get; set; }
        public bool message { get; set; }
    }
}

CepteFaturaMvc/Controllers/EfaturaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Net.Mail;

namespace CepteFaturaMvc.Controllers
{

    public class EfaturaController : Controller
    {
        // GET: Efatura
        public ActionResult Ana_Sayfa()
        {
            return View();
        }

        [HttpPost]


        public JsonResult Ana_Sayfa(Models.Email model)
        {
            MailMessage mailim = new MailMessage();
            mailim.To.Add("bilgi@ceptefaturam.com");
            mailim.From = new MailAddress("bilgi@ceptefaturam.com");
            mailim.Subject = "Bize Ulaşın Sayfasından Mesajınız Var. ";
            mailim.Body = "Ad soyad:" + model.ad + " <br> Mail adresim:" + " " + model.email + " <br>Telefon Numaram:" + model.telefon + " <br>Konu:" + model.konu + " <br>Mesaj:" + model.mesaj;
            mailim.IsBodyHtml = true;



            SmtpClient smtp = new SmtpClient();
            smtp.Credentials = new NetworkCredential("bilgi@ceptefaturam.com", "0M5azs0@");
            smtp.Port = 587;
            smtp.Host = "smtp.ceptefaturam.com";
            smtp.EnableSsl = false;


            try
            {
                smtp.Send(mailim);


            }
            catch (Exception)
            {

            }

            return Json("asdasd");
        }















        public ActionResult Kampanyalar()
        {
            return View();
        }
        public ActionResult Iletisim()
        {
            return View();
        }
        public ActionResult Kullanim_sartlari()
        {
            return View();
        }
        public ActionResult Ozellikler()
        {
            return View();
        }
        public ActionResult Destek()
        {
            return View();
        }
        public ActionResult SSS()
        {
            return View();
        }
        public ActionResult Blog()
        {
            return View();
        }
        public ActionResult EFatura_nedir()
        {
            return View();
        }
      
        public ActionResult EFaturaya_Gecis_Zorunlulugu()
        {
            return View();
        }
        
        public ActionResult Ücretsiz_EFatura_Nasil_Kullanilir()
        {
            return View();
        }
        public ActionResult Blog2()
        {
            return View();
        }
    }
}

CepteFaturaMvc/Views/Efatura/Blog.cshtml
@{
    ViewBag.Title = "Blog";
    Layout = "~/Views/Shread/_Layout.cshtml";
}
<div class="header-text">
    <main id="main">

        <!-- ======= Breadcrumbs ======= -->
        <!--<section id="breadcrumbs" class="breadcrumbs">
            <div class="container">

                <div class="d-flex justify-content-between align-items-center">
                    <h2>Blog</h2>
                    <ol>
                        <li><a href="index.html">Home</a></li>
                        <li>Blog</li>
                    </ol>
                </div>

            </div>
        </section>-->
        <!-- End Breadcrumbs -->
        <!-- ======= Blog Section ======= -->
        <section id="blog" class="blog">
            <div class="container" data-aos="fade-up">
                <div class="row">
                    <div class="col-lg-8 entries">

                        <article class="entry">

                            <div class="entry-img">

                                <img src="~/Content/assets/images/efaturanedir1.jpg"  alt="efatura programi" class="img-fluid">
                            </div>

                            <h2 class="entry-title">
                                <a href="/Efatura/EFatura_Nedir" title="efatura nedir" target="_blank">E-Fatura Nedir? Avantajları Nelerdir?</a>
                            </h2>

                            <div class="entry-meta">
                                <ul>
                                    @*<li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="/Efatura/EFatura_Nedir" target="_blank">John Doe</a></li>*@
                                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="/Efatura/EFatura_Nedir" target="_blank"><time datetime="2020-01-01">01.04.2021</time></a></li>
                                    @*<li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="/Efatura/EFatura_Nedir" target="_blank">12 Comments</a></li>*@
                                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i><a href="/Efatura/EFatura_Nedir" target="_blank"><time datetime="4dk">Okuma Süresi: 4dk</time></a></li>
                                </ul>
                            </div>

                            <div class="entry-content">
                                <p>
                                    <!--1.Yazı-->
                                    E-Fatura sistemi, rahatlık ve kolaylık sağlaması bakımından yaygınlaşıyor.
                                    Müşterilere karşı ve firmalar arası güven ortamı yaratıyor. Hızlı olması nedeniyle zaman ve maliyet tasarrufu sağlıyor.
                                </p>
                                <div class="read-more">
                                    <a href="/Efatura/EFatura_Nedir" title="efatura nedir" target="_blank">Devamını Oku</a>
                                </div>
                            </div>

                        </article>
                        <!--2.YAZI-->
                        <article class="entry">

                            <div class="entry-img">
                                <img src="~/Content/assets2/img/blog/blog2.jpg" alt="e-Irsaliye" class="img-fluid">
                            </div>

                            <h2 class="entry-title">
                                <a href="/Efatura/EFaturaya_Gecis_Zorunlulugu" title="efaturaya geçiş" target="_blank">E-Faturaya Geçiş Zorunluluğu</a>
                            </h2>

                            <div class="entry-meta">
                                <ul>
                                    @*<li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="/Efatura/EFaturaya_Gecis_Zorunlulugu" target="_blank">John Doe</a></li>*@
                                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="/Efatura/EFaturaya_Gecis_Zorunlulugu" target="_blank"><time datetime="2020-01-01">20.05.2021</time></a></li>
                                    @*<li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="/Efatura/EFaturaya_Gecis_Zorunlulugu" target="_blank">12 Comments</a></li>*@
                                    <li class="d-flex align-items-center"><i class="bi bi-clock"></i><a href="/Efatura/EFaturaya_Gecis_Zorunlulugu" target="_blank"><time datetime="3dk">Okuma Süresi: 3dk</time></a></li>
                                </ul>
                            </div>

                            <div class="entry-content">
                                <p>
                                    <!--2.Yazı-->
                                    01.07.2020 Tarihinden itibaren kapsam içerisinde olan işletmelerin e-fatura uygulamasına dahil olmaları gerekiyor fakat komisyoncu veya tüccar olarak sebze ve meyve ticareti ile iştigal eden mükelleflerin 01.01.2020 tarihinden itibaren e-fatura kullanımına geçmeleri gerekiyor.
                                </p>
                                <div class="read-more">
                                    <a href="/Efatura/EFaturaya_Gecis_Zorunlulugu" title="efaturaya geçiş" target="_blank">Devamını Oku</a>
                                </div>
                            </div>

                        </article>
                        <!-- End blog entry -->

                        <div class="blog-pagination">
                            <ul class="justify-content-center">
                                <li class="active"><a href="/Efatura/Blog" target="_blank">1</a></li>
                                <li><a href="/Efatura/Blog2" title="efatura" target="_blank">2</a></li>
                                @*<li><a href="#">3</a></li>*@
                            </ul>
                        </div>

                    </div><!-- End blog entries list -->

                    <div class="col-lg-4">

                        <div class="sidebar">

                            @*<h3 class="sidebar-title">Ara</h3>
                                <div class="sidebar-item search-form">
                                    <form action="">
                                        <input type="text">
                                        <button type="submit"><i class="bi bi-search"></i></button>
                                    </form>
                                </div>*@
                            <!-- End sidebar search formn-->

                            <h3 class="sidebar-title">Kategoriler</h3>
                            <div class="sidebar-item categories">
                                <ul>
                                    <li><a href="/Efatura/EFatura_Nedir">E-Fatura <span>(3)</span></a></li>                                    
                                    <li><a href="/EFatura/EFaturaya_Gecis_Zorunlulugu">E-Arşiv <span>(1)</span></a></li>
                                    
                                    @*<li><a href="#">Educaion <span>(14)</span></a></li>*@
                                </ul>
                            </div><!-- End sidebar categories-->

                            <h3 class="sidebar-title">Çok Okunanlar</h3>
                            <div class="sidebar-item recent-posts">
                                <div class="post-item clearfix">
                                    <img src="~/Content/assets2/img/blog/blog2.jpg" alt="efatura entegratörü">
                                    <h4><a href="/EFatura/EFaturaya_Gecis_Zorunlulugu" title="efatura geçiş" target="_blank">E-Faturaya Geçiş Zorunluluğu</a></h4>
                                    <time datetime="2020-01-01">20.05.2021</time>
                                </div>

                                <div class="post-item clearfix">

                                    <img src="~/Content/assets/images/efaturanedir1.jpg"   alt="payflex e fatura">
                                    <h4><a href="/Efatura/EFatura_nedir" title="efatura avantajları" target="_blank">E-Fatura Nedir? Avantajları Nelerdir?</a></h4>
                                    <time datetime="2020-01-01">01.04.2021</time>
                                </div>

                                <div class="post-item clearfix">
                                    
                                    <img src="~/Content/assets/images/ücretsizefatura1.jpg" alt="efatura fiyatları">
                                    <h4><a href="/Efatura/Ücretsiz_EFatura_Nasil_Kullanilir" title="ücretsiz efatura" target="_blank">Ücretsiz E-Fatura Nasıl Kullanılır</a></h4>
                                    <time datetime="2020-01-01">09.05.2021</time>
                                </div>
                                
                            </div><!-- End sidebar recent posts-->

                            <h3 class="sidebar-title">Etiketler</h3>
                            <div class="sidebar-item tags">
                                <ul>
                                    <li><a href="/Efatura/Blog">Efatura</a></li>
                                    <li><a href="/Efatura/Blog">Ön Muhasebe</a></li>
                                    <li><a href="/Efatura/Blog">E-İrsaliye</a></li>
                                    <li><a href="/Efatura/Blog">Muhasebe</a></li>
                                    <li><a href="/Efatura/Blog">E-Arşiv</a></li>
                                    <li><a href="/Efatura/Blog">E-Defter</a></li>
                                    @*<li><a href="#">Creative</a></li>
                                        <li><a href="#">Studio</a></li>
                                        <li><a href="#">Smart</a></li>
                                        <li><a href="#">Tips</a></li>
                                        <li><a href="#">Marketing</a></li>*@
                                </ul>
                            </div><!-- End sidebar tags-->

                        </div><!-- End sidebar -->

                    </div><!-- End blog sidebar -->

                </div>

            </div>
        </section><!-- End Blog Section -->

    </main><!-- End #main -->
</div>

CepteFaturaMvc/Views/Efatura/Destek.cshtml
@{
    ViewBag.Title = "Destek";
    Layout = "~/Views/Shread/_Layout.cshtml";
}

<div class="header-text">

    <div class="container">

        <div class="section-title">

            <div class="text-center">
                <h2 style="color: rgb(247, 141, 102)">SİZE ULAŞALIM</h2>
            </div>
        </div>
        <center>
            <form method="post" role="form" id="form" class="php-email-form col-lg-10">
                <div class="row">
                    <div class="col-md-6 form-group ">
                        <input type="text" name="ad" class="form-control" id="ad" style="margin-top:15px; color:#5786b4;border:2px solid #ced4da;" placeholder="Adınız Soyadınız:" data-rule="minlen:4" data-msg="Lütfen Boş Bırakmayınız." />
                    </div>
                    <div class="col-md-6 form-group mt-3 mt-md-0">
                        <input type="email" class="form-control" name="email" id="email" style="margin-top:15px; color:#5786b4;border:2px solid #ced4da;" placeholder="E-Mail Adresiniz:" data-rule="email" data-msg="Lütfen Boş Bırakmayınız." />
                    </div>
                </div>
                <div class="col-md-offset-4 mt-4 col-md-12">
                    <div class="text-center" style="margin-top:30px;border-color: #ec6d3e;"><button type="button" class="btn btn-success">Gönder</button></div>
                </div>
            </form>
        </center>

        <div style="text-align:center; margin-top:50px; margin-bottom: 30px;" class="row contact-info">
            <div class="text-center" style="margin-top:10px; margin-bottom:20px">
            </div>

            <div class="container">
                <h4 style="color: rgb(247, 141, 102);margin-bottom: 30px;">BİZE ULAŞIN</h4>
                <div class="row">
                    <div class="col-md-12">
                        <div class="contact-icon">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </div>
                        
                        <a style="color: black; font-weight: 500; margin-bottom: 30px;" title="bilgi@ceptefaturam.com" href="mailto:">bilgi@ceptefaturam.com</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CepteFaturaMvc/Views/Efatura/Iletisim.cshtml
@{
    ViewBag.Title = "Iletisim";
    Layout = "~/Views/Shread/_Layout.cshtml";
}

<div class="header-text">
    <section id="contact" class="contact">
        <div class="container">

            <div class="section-title">
              <div class="text-center" style="margin-top:10px;"><h2 style="color: #ff7c4d">İLETİŞİM TALEP FORMU</h2></div><br>
                <p style="font-weight: 400; margin-right:10px; font-family:'Poppins', sans-serif; ">
                    <span style="font-size: 15px">
                        E-fatura sistemi hakkında her türlü bilgi, destek ve önerilerinizi form ile bize gönderebilirsiniz.
                        <br>Operatörlerimiz en kısa zamanda sizinle iletişime geçecektir.
                    </span>
                </p>
            </div>
            @model CepteFaturaMvc.Models.Email
            <center>
                <form action="forms/contact.php" method="post" role="form" class="php-email-form col-lg-9">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="text" name="ad" class="form-control" id="ad" style="color:#5786b4;border:2px solid #ced4da;" placeholder="Adınız Soyadınız:" data-rule="" data-msg="Lütfen Boş Bırakmayınız.">
                        </div>
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            <input type="email" class="form-control" name="email" id="email" style="color:#5786b4;border:2px solid #ced4da;" placeholder="E-Mail Adresiniz:" data-rule="email" data-msg="Lütfen Boş Bırakmayınız.">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="text" name="telefon" class="form-control" id="telefon" style="color:#5786b4;border:2px solid #ced4da;" placeholder="Telefon:" data-rule="minlen:4" data-msg="Lütfen Boş Bırakmayınız.">
                        </div>
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            <input type="text" class="form-control" name="konu" id="konu" style="color:#5786b4;border:2px solid #ced4da;" placeholder="Konu:" data-rule="text" data-msg="Lütfen Boş Bırakmayınız.">
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="col-md-12 form-group mt-3 mt-md-0">
                            <textarea id="mesaj" class="form-control" name="mesaj" rows="3" cols="50" style="color:#5786b4;border:2px solid #ced4da;" placeholder="İstek / Öneri" data-msg="Lütfen Boş Bırakmayınız."></textarea>
                        </div>
                    </div>
                    <div class="text-center" style="margin-top:30px"><button type="button" class="btn btn-success">Gönder</button></div>
                </form>
            </center>
            <div class="row contact-info">

                <div class="container">
                    <iframe style="border:0; border-radius:35px; width : 100%; height: 450px; margin-top:30px" src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3015.6605690936153!2d31.170095215262524!3d40.90126003395237!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x409d7558c6d29949%3A0x332d4e256b968190!2sBilsoft!5e0!3m2!1str!2str!4v1621942997800!5m2!1str!2str" width="600" height="450"  allowfullscreen="" loading="lazy"></iframe>
                </div>
            </div>
        </div>

CepteFaturaMvc/Views/Shread/_Layout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>


    <!-- Google Tag Manager -->

    <script>
        (function (w, d, s, l, i) {
        w[l] = w[l] || []; w[l].push({
        'gtm.start':
        new Date().getTime(), event: 'gtm.js'
        }); var f = d.getElementsByTagName(s)[0],
        j = d.createElement(s), dl = l != 'dataLayer' ? '&l=' + l : ''; j.async = true; j.src =
        'https://www.googletagmanager.com/gtm.js?id=' + i + dl; f.parentNode.insertBefore(j, f);
        })(window, document, 'script', 'dataLayer', 'GTM-KF9ZMVQ');
    </script>
    <!-- End Google Tag Manager -->

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="keywords" content="payflex e fatura, ucretsiz efatura, fatura,
          e-Fatura, e-Irsaliye,e fatura, ücretsiz efatura, efatura başvuru,
          efatura fiyatları, efatura entegratörü,ceptefatura, efatura programi, e-arsiv" />
    <meta name="description" content="Ücretsiz E-Fatura Platformu Sayesinde Ön Muhasebe İşlemlerinizi Sadeleştirin, Kolaylaştırın ve Hızlandırın | ücretsiz efatura,ceptefatura, e-Fatura, e-Arşiv, e-İrsaliye, e-Defter, " />
    <meta name="google-site-verification" content="ltjQLHfs2UarGRpM1smzYcquFMlcVkIh7hvrTxM5sak" />
    <meta name="publisher" content="VS 2019" />
    <meta name="author" content="bilsoft" />
    <meta name="copyright" content="Bilsoft Yazılım"/>
    <meta name="robots" content="index, follow" />
    <meta name="twitter:card" content="summary" />
    <meta name="twitter:url" content="https://twitter.com/CepteFaturam" />
    <meta name="twitter:site" content="CepteFaturam" />
    <meta name="twitter:image" content="https://www.ceptefaturam.com/Content/assets/images/resized_logoooo123.png" />
    <meta name="twitter:description" content="e-Fatura, ceptefaturam.com, dijital dönüşüm, ücretsiz efatura, efatura portal, e-irsaliye, e-arşiv, efatura programi" />
    <meta property="og:type" content="yazılım" />
    <meta property="og:locale" content="tr_TR" />
    <meta property="og:title" content="Cepte Faturam & E-Fatura Ücretsiz Dijital Dönüşüm" />
    <meta property="og:url" content="https://www.ceptefaturam.com/" />
    <meta property="og:image" content="https://wwww.ceptefaturam.com/Content/assets/images/logoooo.png" />
    <meta property="og:description" content="ÜCRETSİZ E-FATURA DÜNYASINA HOŞGELDİNİZ!" />

    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet" />



    <title>Cepte Faturam & E-Fatura Ücretsiz Dijital Dönüşüm</title>

    <link href="~/Content/assets/images/favicon.jpg" rel="icon" />
    <link href="~/Content/assets/images/favicon.jpg" rel="apple-touch-icon" />
    <link href="~/Content/assets2/css/style2.css" rel="stylesheet" />
    <link href="~/Content/assets/css/style.css" rel="stylesheet" />
    <link href="~/Content/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/assets/css/font-awesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css/templatemo-lava.css" rel="stylesheet" />
    <link href="~/Content/assets/css/owl-carousel.css" rel="stylesheet" />
    <link href="~/Content/assets/css1/fontawesome.css" rel="stylesheet" />
    <link href="~/Content/assets/css1/templatemo-finance-business.css" rel="stylesheet" />
    <link href="~/Content/assets/css1/owl.css" rel="stylesheet" />
    <?xml version="1.0" encoding="UTF-8" ?>
    <sitemapindex xmlns="http://www.ceptefaturam.com/Content/sitemap.xml">

    </sitemapindex>
    


</head>

<!--Start of Tawk.to Script-->

<script type="text/javascript">
    var Tawk_API = Tawk_API || {}, Tawk_LoadStart = new Date();
    (function () {
        var s1 = document.createElement("script"), s0 = document.getElementsByTagName("script")[0];
        s1.async = true;
        s1.src = 'https://embed.tawk.to/60bf1eaa4ae6dd0abe7d1081/1f7l8viim';
        s1.charset = 'UTF-8';
        s1.setAttribute('crossorigin', '*');
        s0.parentNode.insertBefore(s1, s0);
    })();
</script>
<!--End of Tawk.to Script-->

<body>
    <!-- Google Tag Manager (noscript) -->
    <noscript>
        <iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KF9ZMVQ"
                height="0" width="0" style="display:none;visibility:hidden"></iframe>
    </noscript>
    <!-- End Google Tag Manager (noscript) -->

    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>

    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                   <div class="col-11">
                       <nav class="main-nav">
                           <a href="/Efatura/Ana_Sayfa" title="Anasayfa" class="logo">

                               <img id="logoMobil" style="max-width:240px;" src="~/Content/assets/images/logoooo.png" alt="ceptefatura" >
                           </a>
                           <ul class="nav">

                               <li class="scroll-to-section"><a href="/Efatura/Ana_Sayfa" title="Ceptefaturam Anasayfa" class="">ANASAYFA</a></li>
                               <li class="scroll-to-section"><a href="/Efatura/Ozellikler" title="Ceptefaturam Özellikler" class="">ÖZELLİKLER</a></li>
                               <li class="scroll-to-section"><a href="/Efatura/Kampanyalar" title="Ceptefaturam Kampanyalar" class="">KAMPANYALAR</a>
                               <li class="scroll-to-section"><a href="/Efatura/SSS" title="Sıkça sorulan sorular" class="">S.S.S</a>
                               <li class="scroll-to-section"><a href="/Efatura/BLOG" title="Ceptefaturam Blog" class="">BLOG</a>
                               <li class="scroll-to-section"><a href="/Efatura/Destek" title="Ceptefaturam Destek" class="">DESTEK</a>
                               <li class="scroll-to-section"><a href="/Efatura/Iletisim" title="Ceptefaturam İletişim" class="">İLETİŞİM</a></li>
                           </ul>
                           <a class='menu-trigger' title="Menu">
                               <span>Menu</span>
                           </a>
                       </nav>
                   </div>
                   <div class="col-1">
                       
                         <a href="~/setup/sanalfatura.msi" id="btnIndir" title="Ücretsiz efatura programı">HEMEN İNDİR</a>

                       
                   </div>
            </div>
        </div>
    </header>
    @RenderBody()
<section id="footer">
    <footer>
        <div class="container">
            <div class="row">

                <div class="col-md-4 footer-item">
                    <div style="font-weight:600;">
                        <li id="mailMobil" >e-mail:<a style="color:black;" href="mailto:" title="bilgi@ceptefaturam.com"> bilgi@ceptefaturam.com</a></li>
                    </div>

                    <ul class="social-icons">
                        <li><a href="https://www.facebook.com/profile.php?id=100069136936659" target="_blank"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="https://www.instagram.com/ceptefaturam/" target="_blank"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="https://twitter.com/CepteFaturam" target="_blank"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="https://www.linkedin.com/in/cepte-faturam-0b8161214/?originalSubdomain=tr" target="_blank"><i class="fa fa-linkedin"></i></a></li>
                    </ul>

                </div>
                <div class="col-md-4 footer-item">
                    <h4>Sayfa Linkleri</h4>
                    <ul class="menu-list">
                        <li><a href="/Efatura/Ana_Sayfa"title="Anasayfa" >Anasayfa</a></li>
                        <li><a href="/Efatura/Ozellikler" title="Özellikler">Özellikler</a></li>
                        <li><a href="/Efatura/Kampanyalar" title="Kampanyalar">Kampanyalar</a></li>
                        <li><a href="/Efatura/SSS" title="SSS">Sıkça Sorulan Sorular</a></li>
                        <li><a href="/Efatura/Destek" title="Destek">Destek</a></li>
                        <li><a href="/Efatura/Iletisim" title="İletişim">İletişim</a></li>
                    </ul>
                </div>
                <div class="col-md-4 footer-item">
                    <h4>Özellikler</h4>
                    <ul class="menu-list">
                        <li><a href="/Efatura/Ozellikler" title="efatura modül">Fatura Modulü</a></li>
                        <li><a href="/Efatura/Ozellikler" title="efatura cari kart">Cari Kart Modulü</a></li>
                        <li><a href="/Efatura/Ozellikler" title="efatura stok">Stok Takibi Modulü</a></li>
                        <li><a href="/Efatura/Ozellikler" title="efatura rapoarlama">Raporlama Sistemi</a></li>
                        <li><a href="/Efatura/Ozellikler" title="efatura arşivleme">Arşivleme</a></li>
                        <li><a href="/Efatura/Ozellikler" title="efatura gönderme">Gönderme</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </footer>
    
    <div class="sub-footer">

        <div class="container">            
            <div class="copyright">
                &copy; Copyright <strong><span>CepteFaturam</span></strong>. Tüm Hakları Saklıdır. Ceptefaturam bir <a id="ayri" href="https://www.bilsoft.com/" title="www.bilsoft.com"> Bilsoft Yazılım </a>  Kuruluşudur. &nbsp;<a href="Kullanim_sartlari" title="Kullanım Şartları" >Çerez Politikası</a>
            </div>
        </div>
    </div>

    <script src="~/Content/assets/js/jquery-2.1.0.min.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>
    <script src="~/Content/assets/js/popper.js"></script>
    <script src="~/Content/assets/js/owl-carousel.js"></script>
    <script src="~/Content/assets/js/scrollreveal.min.js"></script>
    <script src="~/Content/assets/js/waypoints.min.js"></script>
    <script src="~/Content/assets/js/imgfix.min.js"></script>
    <script src="~/Content/assets/js/jquery.counterup.min.js"></script>
    <script src="~/Content/assets/js/custom.js"></script>

    @model CepteFaturaMvc.Models.Email

    <script>
        $("form button.btn").on("click", function () {

            let mail = {
                "ad": $("input#ad").val(),
                "telefon": $("input#telefon").val(),
                "email": $("input#email").val(),
                "konu": $("input#konu").val(),
                "mesaj": $("textarea#mesaj").val(),
            };
           
       
            $.ajax({
                url: "@Url.Action("Ana_Sayfa","Efatura")",
                type: "post",
                dataType: "JSON",
                data: mail,
                success: function (res) {
                    console.log(res)
                    if (res.IsSuccess) {

                    } else { }
                    for (var i = 0; i < 5; i++) {
                        $("form")[i].reset()
                    }

                },
                error: function () {

                }
            });

            return false;
        })

    </script>
</section>
</body>
</html>